---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

params:
  ACCESS_KEY_ID:
  SECRET_KEY:

inputs:
- name: cf-cli-release-input
- name: cli-binary-linux-64

outputs:
  - name: candidate-release
  - name: cf-cli-release-output

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cp -r cf-cli-release-input/. cf-cli-release-output

    cd cf-cli-release-output

    git config --global user.email cf-cli-eng@pivotal.io
    git config --global user.name "CI Bot"

    git fetch origin master:refs/remotes/origin/master
    git rebase origin/master

    CLI_VERSION=$(cat cli-binary-linux-64/version)

    cat << EOF > config/private.yml
    blobstore:
      options:
        access_key_id: "$ACCESS_KEY_ID"
        secret_access_key: "$SECRET_KEY"
    EOF

    old_blob_path=$(bosh blobs --column=path)
    bosh remove-blob $old_blob_path

    bosh add-blob ../cli-binary-linux-64/cf-cli_${CLI_VERSION}_linux_x86-64.tgz cf-cli_${CLI_VERSION}_linux_x86-64.tgz
    bosh upload-blobs

    git add --all .
    git commit -m "bump cli to ${CLI_VERSION}"

    bosh create-release --timestamp-version --tarball=../candidate-release/cf-cli-dev-release.tgz
