---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-release-base

params:
  ACCESS_KEY_ID:
  SECRET_KEY:

inputs:
- name: cf-cli-release-input
- name: release-version

outputs:
- name: cf-cli-release-output

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    RELEASE_VERSION=$(cat release-version/version)

    cp -r cf-cli-release-input/. cf-cli-release-output

    cd cf-cli-release-output

    git config --global user.email cf-cli-eng@pivotal.io
    git config --global user.name "CI Bot"

    bosh create-release --final --version="${RELEASE_VERSION}"

    git add --all
    git status
    git commit -m "create final release ${RELEASE_VERSION}"
    git tag v${RELEASE_VERSION}
