---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-release-base

inputs:
- name: cf-cli-release
- name: bbl-store
- name: bosh-lite-lock

run:
  path: bash
  args:
  - -c
  - |
    set -e

    ENV=$(cat bosh-lite-lock/name | cut -d "." -f 1)
    pushd bbl-store/ci/infrastructure/$ENV
      eval "$(bbl print-env)"
    popd

    set -x
    cd cf-cli-release
    ./tests/run.sh
