---
resources:
- name: cf-cli-release
  type: git
  source:
    uri: https://github.com/bosh-packages/cf-cli-release
    private_key: ((release-repo-github-key))
    branch: wip-ci
    ignore_paths:
      - config/*
      - releases/*
      - .final_builds/*

- name: cli-binary-linux-64
  type: s3
  source:
    bucket: cf-cli-releases
    regexp: releases/v(.*)/cf-cli_(.*)_linux_x86-64.tgz
    region_name: us-west-1

- name: candidate-release
  type: s3
  source:
    bucket: cf-cli-bosh-release
    versioned_file: cf-cli-dev-release.tgz
    access_key_id: ((release-bucket-access-key-id))
    secret_access_key: ((release-bucket-secret-key))
    region_name: us-west-1

# - name: release-version
#   type: semver
#   source:
#     access_key_id: ((release-bucket-access-key-id))
#     secret_access_key: ((release-bucket-secret-key))
#     initial_version: 1.0.0
#     bucket: cf-cli-bosh-release
#     key: version
#     region_name: us-west-1
#
jobs:
  - name: update-cli
    plan:
      - aggregate:
        - get: cf-cli-release
          trigger: true
        - get: cli-binary-linux-64
          trigger: true
      - task: bump-cli
        file: cf-cli-release/ci/tasks/bump-cli-release.yml
        input_mapping:
          cf-cli-release-input: cf-cli-release
        params:
          ACCESS_KEY_ID: ((release-bucket-access-key-id))
          SECRET_KEY: ((release-bucket-secret-key))
      - put: candidate-release
        params:
          file: "candidate-release/cf-cli-dev-release.tgz"
      - put: cf-cli-release
        params:
          repository: cf-cli-release-output


    #TODO (tv, sv) run tests/run.sh against release
  # - name: run-tests
  #   serial: true
  #   plan: do-stuff
  # - aggregate:
  #   - get: cf-cli-release
  #     passed: update-cli
  #     trigger: true
  #
  # - name: update-release
  #   serial: true
  #   plan:
  #     - aggregate:
  #       - get: cf-cli-release
  #         passed: run-tests
  #         trigger: true
  #       - get: cli-binary-linux-64
  #         passed: run-tests
  #         trigger: true
  #       - get: release-version
  #         params:
  #           bump: minor
  #       - task: update-release
  #         path: tasks/bump-cli-release.yml
  #         params:
  #           ACCESS_KEY_ID: ((release-bucket-access-key-id))
  #           SECRET_KEY: ((release-bucket-secret-key))
  #       - put: release-version
  #         params:
  #           bump: minor
  #       - put: cf-cli-release
