---
resources:
- name: bbl-store
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-private
    private_key: ((private-repo-github-key))
    branch: master

- name: cf-cli-release
  type: git
  source:
    uri: git@github.com:bosh-packages/cf-cli-release
    private_key: ((release-repo-github-key))
    branch: wip-ci
    ignore_paths:
      - config/*
      - releases/*
      - .final_builds/*

- name: cf-cli-release-final
  type: git
  source:
    uri: git@github.com:bosh-packages/cf-cli-release
    private_key: ((release-repo-github-key))
    branch: wip-ci

- name: gh-release
  type: github-release
  source:
    owner: bosh-packages
    repository: cf-cli-release
    access_token: ((private-repo-github-key))
    drafts: true

- name: gcp-bosh-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: ((pools-repo-github-key))
    branch: master
    pool: baked-potato

- name: cli-binary-linux-64
  type: s3
  source:
    bucket: cf-cli-releases
    regexp: releases/v(.*)/cf-cli_(.*)_linux_x86-64.tgz
    region_name: us-west-1

- name: candidate-release
  type: s3
  source:
    bucket: cf-cli-bosh-release
    versioned_file: cf-cli-dev-release.tgz
    access_key_id: ((release-bucket-access-key-id))
    secret_access_key: ((release-bucket-secret-key))
    region_name: us-west-1

- name: release-version
  type: semver
  source:
    access_key_id: ((release-bucket-access-key-id))
    secret_access_key: ((release-bucket-secret-key))
    initial_version: 1.1.0
    bucket: cf-cli-bosh-release
    key: version
    region_name: us-west-1

jobs:
  - name: update-cli
    plan:
      - aggregate:
        - get: cf-cli-release
          trigger: true
        - get: cli-binary-linux-64
          trigger: true
      - task: bump-cli
        file: cf-cli-release/ci/tasks/bump-cli-release.yml
        input_mapping:
          cf-cli-release-input: cf-cli-release
        params:
          ACCESS_KEY_ID: ((release-bucket-access-key-id))
          SECRET_KEY: ((release-bucket-secret-key))
      - put: candidate-release
        params:
          file: "candidate-release-output/cf-cli-dev-release.tgz"
      - put: cf-cli-release
        params:
          repository: cf-cli-release-output
          rebase: true

  - name: run-tests
    serial: true
    plan:
    - aggregate:
      - get: cf-cli-release
        passed: [update-cli]
        trigger: true
      - get: bbl-store
      - put: bosh-lite-lock
        resource: gcp-bosh-pool
        params:
          acquire: true
    - do:
      - task: run-tests
        file: cf-cli-release/ci/tasks/run-tests.yml
    ensure:
      put: gcp-bosh-pool
      params:
        release: bosh-lite-lock

  - name: finalize-release
    serial: true
    plan:
      - aggregate:
        - get: cf-cli-release
          passed: [run-tests]
          trigger: true
        - get: release-version
          params:
            bump: minor
      - task: finalize-release
        file: cf-cli-release/ci/tasks/finalize-release.yml
        params:
          ACCESS_KEY_ID: ((release-bucket-access-key-id))
          SECRET_KEY: ((release-bucket-secret-key))
      - put: release-version
        params:
          file: release-version/version
      - put: cf-cli-release-final
        params:
          repository: cf-cli-release-output
          rebase: true
      - put: gh-release
        params:
          name: release-version/version
          tag: release-version/version
          tag_prefix: v
